### ISSUE TITLE
Auth MVP

### ISSUE THREAD

**Issue by mmcnulty20** [arieltlr/PinandNeedle#3]
- [x] Add more images to splash with fade to white at the bottom
- [x] Sign up modal a bit wider
- [ ] Remove hover effect from auth modal buttons (continue as demo user/continue/log in)
- [x] Larger circle on hover around x button on modal
- [x] Modals need box-shadow - seems as though rule exists but isn’t properly applying
- [x] Adjust height of log in modal for less white space at the bottom
- [x] (completely optional) Fonts are often slightly off-black rather than pure black, and it can make them look a little more clean/less stark
- [x] Larger/lower weight font for errors
- [x] Dropdown hover effects should have more padding to left

**Comment by arieltlr** [comment]
Hi Megan - thanks for the review! I'm glad you told me that black is usually an off-black. I think that makes it look a lot better and I would never have thought to try that. Thanks for the font weight call out too - I meant to go download a lower weight of the same font and completely forgot. There are a few places I am going to apply the same lower weight styling. 

I think you meant to write, _add hover effect_ to the modal buttons. I double checked Pinterest and their buttons have hover and mine did not (accidentally lost it trying to get the hover effect correct on the search bar). I added cursor hover effect to the buttons. 

I moved the auth-mvp back into the ready for revision column.

**Comment by mmcnulty20** [comment]
- [x] Cursor pointer when hovering over modal x

I did mean remove! You have a darkening effect on the buttons at the bottom of the forms (continue/continue as demo user on sign up modal, log in/continue as demo user on log in modal) that Pinterest does not have.

Looking really great! These are super minor changes and don't need to be high-priority.

**Comment by arieltlr** [comment]
Made the fixes and pushed to Heroku!

**Comment by mmcnulty20** [comment]
Amazing work! :)
